### ISSUE TITLE
New Changes in Issue 13

### ISSUE THREAD

**Issue by GamzeUnlu95** [jasonrwang/ghg_analytics#17]
I created the dictionary. We can check where we want to use it. 

For the graph: #Sorted bar chart of 2012 greenhouse gases. 
I am using the ghgDf_merged data frame to be able to work on year 2014. Filled the missing values for 2013 and 2014. The graph works fine for 2012. The moment I change it to 2013 or 2014, there is an error. Couldn't figure out why.?? 

Same for the graph: # Time series for ghg emissions of the top 10 most polluting countries.
The same code is not working with the merged data frame even for 2012. 
So these two graphs are still for 2012. 

I put the differences on the graph 2030 NDCs. vs 2030 projections. 

For the scatter plot graph, when I try to divide it into four whole graph is shifted and does not look really nice now. I commented out that part. Will check on Wednesday, when we meet. I have no more time today :(

**Comment by jasonrwang** [comment]
Interesting, but we can just use `ghgDf_PIK` instead of `ghgDf_merged`.

The issue is because the years until 2012 are stored as strings and 2013 and 2014 are stored as integers – oops! For example, `ghgDf_merged['2014']` won't work, but `ghgDf_merged[2014]` will.

FYI, it tries to plot `HistoricalDebtMergedDf` before that variable is declared right now. Though was that part of @Mittal-A's work?
